from os import getenv

BACKEND_HOSTNAME = getenv('BACKEND_HOSTNAME', 'http://localhost')
BACKEND_PORT = getenv('BACKEND_PORT', '5000')
BACKEND_PROJECTS =  getenv('BACKEND_PROJECTS', 'projects') 
BACKEND_PROJECTS_FULL_PATH = f'{BACKEND_HOSTNAME}:{BACKEND_PORT}/{BACKEND_PROJECTS}'