@hostname = http://localhost:5000
@project_path = projects
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjQ3MzI5MSwianRpIjoiYmZlNWFkNDctODUyYS00MTkxLWFjNWQtZGI1ZDQ5MzlkZGExIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NDY0NzMyOTEsImNzcmYiOiIwMTQyNjAwZC1lNzg3LTRmNTItOGE1Zi0xMzNkNGVhNTU5MGYiLCJleHAiOjE3NDY0NzQxOTF9.yDR2H-dp4PAHm-QjqayTbIFR0ySk3r_23G0vI0LOyFQ

###
GET {{hostname}}/{{project_path}}/choir
### 
GET {{hostname}}/{{project_path}}/choir/1

###
GET {{hostname}}/{{project_path}}/contact
### 
GET {{hostname}}/{{project_path}}/contact/1

###
GET {{hostname}}/{{project_path}}/location
### 
GET {{hostname}}/{{project_path}}/location/1

###
GET {{hostname}}/{{project_path}}/music
### 
GET {{hostname}}/{{project_path}}/music/1

###
GET {{hostname}}/{{project_path}}/music_project
### 
GET {{hostname}}/{{project_path}}/music_project/1

###
GET {{hostname}}/{{project_path}}/part_allocation
###
GET {{hostname}}/{{project_path}}/part_allocation?project_id=1
### 
GET {{hostname}}/{{project_path}}/part_allocation/1

###
GET {{hostname}}/{{project_path}}/role

###
GET {{hostname}}/{{project_path}}/role?project_id=12
### 
GET {{hostname}}/{{project_path}}/role/90
Authorization: Bearer {{ access_token }}

### 
GET {{hostname}}/{{project_path}}/task
Authorization: Bearer {{ access_token }}
### 
GET {{hostname}}/{{project_path}}/task/45
Authorization: Bearer {{ access_token }}
### 
GET {{hostname}}/{{project_path}}/task?filter=Palestrina and Marenzio&sort=older


