@hostname_auth = http://localhost:5002
@hostname = http://localhost:5000
@project_path = projects

###
GET {{hostname}}/{{project_path}}/choir
### 
GET {{hostname}}/{{project_path}}/choir/1

###
GET {{hostname}}/{{project_path}}/contact
### 
GET {{hostname}}/{{project_path}}/contact/1

###
GET {{hostname}}/{{project_path}}/location
### 
GET {{hostname}}/{{project_path}}/location/1

###
GET {{hostname}}/{{project_path}}/music
### 
GET {{hostname}}/{{project_path}}/music/1

###
GET {{hostname}}/{{project_path}}/music_project
### 
GET {{hostname}}/{{project_path}}/music_project/1

###
GET {{hostname}}/{{project_path}}/part_allocation
###
GET {{hostname}}/{{project_path}}/part_allocation?project_id=1
### 
GET {{hostname}}/{{project_path}}/part_allocation/1

###
GET {{hostname}}/{{project_path}}/role
###
GET {{hostname}}/{{project_path}}/role?project_id=12
### 
GET {{hostname}}/{{project_path}}/role/90

### 
GET {{hostname}}/{{project_path}}/task
### 
GET {{hostname}}/{{project_path}}/task/45
### 
GET {{hostname}}/{{project_path}}/task?filter=Palestrina and Marenzio&sort=older

###
POST {{hostname_auth}}/api/register HTTP/1.1
content-type: application/json

{
    "email": "user1@fake.email",
    "password": "12345"
}

###
POST {{hostname_auth}}/api/login
content-type: application/json

{
    "email": "user1@fake.email",
    "password": "12345"
}

###
GET {{hostname_auth}}/api/user/1
###
GET {{hostname_auth}}/api/users?email=enr.ruggiceri.mail@gmail.com&cazzi=amari
###
DELETE {{hostname_auth}}/api/user/3
